### ISSUE TITLE
Username misattributed

### ISSUE THREAD

**Issue by andylash** [thesaucecode/meteor-rollbar#8]
I noticed that in this package, instead of using the standard Meteor users.username field, you're using users.profile.name.  That's also pretty standard, but not unique like username.  I suspect for most apps users.profile.name is the wrong string.

**Comment by rjerrems** [comment]
We have only had people ask to use users.profile.name so far. I am happy to have meteor.username as well, but it probably should be configurable because it is a developer preference - what do you think?

Rohan

**Comment by em0ney** [comment]
Thanks for the comment @andylash 

profile.username is infact the meteor default and I have set this to be the package default for now, with the aim to make this configurable in the future.

cheers,
Elliott

**Comment by em0ney** [comment]
Resolved in version v0.0.8
